'use strict';


/**
 * The list of languages available.
 */
var languages = {
  'AB': 'Abkhazian',
  'AA': 'Afar',
  'AF': 'Afrikaans',
  'SQ': 'Albanian',
  'AM': 'Amharic, Ameharic',
  'AR': 'Arabic',
  'HY': 'Armenian',
  'AS': 'Assamese',
  'AY': 'Aymara',
  'AZ': 'Azerbaijani',
  'BA': 'Bashkir',
  'EU': 'Basque',
  'BN': 'Bengali, Bangla',
  'DZ': 'Bhutani',
  'BH': 'Bihari',
  'BI': 'Bislama',
  'BR': 'Breton',
  'BG': 'Bulgarian',
  'MY': 'Burmese',
  'BE': 'Byelorussian',
  'KM': 'Cambodian',
  'CA': 'Catalan',
  'ZH': 'Chinese',
  'CO': 'Corsican',
  'HR': 'Hrvatski (Croatian)',
  'CS': 'Czech (Ceske)',
  'DA': 'Dansk (Danish)',
  'NL': 'Dutch (Nederlands)',
  'EN': 'English',
  'EO': 'Esperanto',
  'ET': 'Estonian',
  'FO': 'Faroese',
  'FJ': 'Fiji',
  'FI': 'Finnish',
  'FR': 'French',
  'FY': 'Frisian',
  'GL': 'Galician',
  'KA': 'Georgian',
  'DE': 'Deutsch (German)',
  'EL': 'Greek',
  'KL': 'Greenlandic',
  'GN': 'Guarani',
  'GU': 'Gujarati',
  'HA': 'Hausa',
  'IW': 'Hebrew',
  'HI': 'Hindi',
  'HU': 'Hungarian',
  'IS': 'Islenka (Icelandic)',
  'IN': 'Indonesian',
  'IA': 'Interlingua',
  'IE': 'Interlingue',
  'IK': 'Inupiak',
  'GA': 'Irish',
  'IT': 'Italian',
  'JA': 'Japanese',
  'JW': 'Javanese',
  'KN': 'Kannada',
  'KS': 'Kashmiri',
  'KK': 'Kazakh',
  'RW': 'Kinyarwanda',
  'KY': 'Kirghiz',
  'RN': 'Kirundi',
  'KO': 'Korean',
  'KU': 'Kurdish',
  'LO': 'Laothian',
  'LA': 'Latin',
  'LV': 'Latvian, Lettish',
  'LN': 'Lingala',
  'LT': 'Lithuanian',
  'MK': 'Macedonian',
  'MG': 'Malagasy',
  'MS': 'Malay',
  'ML': 'Malayalam',
  'MT': 'Maltese',
  'MI': 'Maori',
  'MR': 'Marathi',
  'MO': 'Moldavian',
  'MN': 'Mongolian',
  'NA': 'Nauru',
  'NE': 'Nepali',
  'NO': 'Norwegian (Norsk)',
  'OC': 'Occitan',
  'OR': 'Oriya',
  'OM': 'Afan (Oromo)',
  'PA': 'Panjabi',
  'PS': 'Pashto, Pushto',
  'FA': 'Persian',
  'PL': 'Polish',
  'PT': 'Portuguese',
  'QU': 'Quechua',
  'RM': 'Rhaeto-Romance',
  'RO': 'Romanian',
  'RU': 'Russian',
  'SM': 'Samoan',
  'SG': 'Sangho',
  'SA': 'Sanskrit',
  'GD': 'Scots Gaelic',
  'SH': 'Serbo-Crotain',
  'ST': 'Sesotho',
  'SR': 'Serbian',
  'TN': 'Setswana',
  'SN': 'Shona',
  'SD': 'Sindhi',
  'SI': 'Singhalese',
  'SS': 'Siswati',
  'SK': 'Slovak',
  'SL': 'Slovenian',
  'SO': 'Somali',
  'ES': 'Spanish (Espanol)',
  'SU': 'Sundanese',
  'SW': 'Swahili',
  'SV': 'Svenska (Swedish)',
  'TL': 'Tagalog',
  'TG': 'Tajik',
  'TT': 'Tatar',
  'TA': 'Tamil',
  'TE': 'Telugu',
  'TH': 'Thai',
  'BO': 'Tibetian',
  'TI': 'Tigrinya',
  'TO': 'Tonga',
  'TS': 'Tsonga',
  'TR': 'Turkish',
  'TK': 'Turkmen',
  'TW': 'Twi',
  'UK': 'Ukranian',
  'UR': 'Urdu',
  'UZ': 'Uzbek',
  'VI': 'Vietnamese',
  'VO': 'Volapuk',
  'CY': 'Welsh',
  'WO': 'Wolof',
  'JI': 'Yiddish',
  'YO': 'Yoruba',
  'XH': 'Xhosa',
  'ZU': 'Zulu'
};
